anatomicalTemplate  :  /path/to/data/{site}/{participant}/anat.nii.gz  

functionalTemplate  :   /path/to/data/{site}/{participant}/func.nii.gz 

subjectList  :  None 

exclusionSubjectList  :  None 

siteList  :  AnnArbor_a

scanParametersCSV  :  /path/to/data/scan_parameters_fcon.csv

outputSubjectListLocation  :   /path/to/data/subjectlistoutput/

subjectListName : ['FCON']
