anatomicalTemplate  :  /path/to/data/{site}/{participant}/anat.nii.gz  

functionalTemplate  :   /path/to/data/{site}/{participant}/func.nii.gz 

subjectList  :  None 

exclusionSubjectList  :  None 

siteList  :  Rockland

scanParametersCSV  :  /path/to/data/scan_parameters_nki.csv

outputSubjectListLocation  :   /path/to/data/subjectlistoutput/

subjectListName : ['NKI-RS']
